[package]
name = "rtt"
version = "0.2.2"
description = "Rapidly-Exploring random trees path planning algorithm."
license = "MIT"
authors = ["Alexey Voznyuk <me@swizard.info>"]

[dependencies]

[dev-dependencies]
rand = "0.4"
